# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps_tv/common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps_tv/common

PRODUCT_COPY_FILES += \
    vendor/gapps_tv/common/proprietary/product/etc/permissions/privapp-permissions-atv-product.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-atv-product.xml \
    vendor/gapps_tv/common/proprietary/product/etc/permissions/privapp-permissions-google-p.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-google-p.xml \
    vendor/gapps_tv/common/proprietary/product/etc/sysconfig/google-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google-hiddenapi-package-whitelist.xml \
    vendor/gapps_tv/common/proprietary/product/etc/sysconfig/google.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google.xml \
    vendor/gapps_tv/common/proprietary/product/etc/sysconfig/google_atv.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/google_atv.xml \
    vendor/gapps_tv/common/proprietary/system_ext/etc/permissions/privapp-permissions-google-se.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-google-se.xml

PRODUCT_PACKAGES += \
    GoogleCalendarSyncAdapter \
    talkback \
    AtvRemoteService \
    Backdrop \
    Katniss \
    SetupWraithPrebuilt \
    SssAuthbridgePrebuilt \
    Tubesky \
    GoogleFeedback \
    GoogleOneTimeInitializer \
    GoogleServicesFramework

PRODUCT_SOONG_NAMESPACES += vendor/gapps_tv/overlay
PRODUCT_PACKAGES += ATVOverlay
