# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps_tv/arm/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps_tv/arm


PRODUCT_PACKAGES += \
    AndroidMediaShell \
    PrebuiltGmsCorePano

$(call inherit-product, vendor/gapps_tv/common/common-vendor.mk)
