# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps/arm/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps/arm


PRODUCT_PACKAGES += \
    AndroidMediaShell \
    PrebuiltGmsCorePano

$(call inherit-product, vendor/gapps/common/common-vendor.mk)
