# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/gapps_tv/arm64/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/gapps_tv/arm64


PRODUCT_PACKAGES += \
    GoogleExtShared \
    GoogleCalendarSyncAdapter \
    GoogleTTS \
    talkback \
    AndroidMediaShell \
    GoogleOneTimeInitializer \
    PrebuiltGmsCorePano \
    Tubesky \
    GoogleFeedback \
    GoogleServicesFramework

ifneq ($(GMS_VARIANT),minimal)

PRODUCT_PACKAGES += \
    TVLauncher \
    TVRecommendations
endif

$(call inherit-product, vendor/gapps_tv/common/common-vendor.mk)
